version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fitpro-rabbitmq
    ports:
      - "5672:5672"     # Puerto de comunicación AMQP
      - "15672:15672"   # Interfaz web de RabbitMQ
    networks:
      - fitpro-network

  auth-db:
    image: postgres:15
    container_name: fitpro-auth-db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: authdb
    ports:
      - "5432:5432"
    volumes:
      - authdb-data:/var/lib/postgresql/data
    networks:
      - fitpro-network

  user-db:
    image: postgres:15
    container_name: fitpro-user-db
    environment:
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: userservice
    ports:
      - "5433:5432"
    volumes:
      - userdb-data:/var/lib/postgresql/data
    networks:
      - fitpro-network

  auth-service:
    build:
      context: ./AuthService
      dockerfile: AuthService.API/Dockerfile
    container_name: fitpro-auth-service
    ports:
      - "5001:80"
    depends_on:
      - auth-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - fitpro-network

  user-service:
    build:
      context: ./UserService
      dockerfile: UserService.API/Dockerfile
    container_name: fitpro-user-service
    ports:
      - "5002:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - fitpro-network
    depends_on:
      - rabbitmq

volumes:
  authdb-data:
  userdb-data:

networks:
  fitpro-network:
    driver: bridge
